# Generated by Django 4.2.27 on 2026-02-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sauna',
            options={'ordering': ['display_order']},
        ),
        migrations.AddField(
            model_name='sauna',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
